blank_issues_enabled: false
contact_links:
  - name: Feature & Change Request
    url: https://github.com/jensrossbach/node-red-contrib-chronos/discussions/categories/ideas-requests
    about: Suggest an idea or request a change for this project
  - name: Discussion Forum
    url: https://github.com/jensrossbach/node-red-contrib-chronos/discussions
    about: Please use the forum for asking questions and getting help, providing feedback and discussing new ideas and enhancements.
